### ISSUE TITLE
라우팅 이슈 수정사항 

### ISSUE THREAD

**Issue by ParkSohyunee** [Team2-Project-OpenMind/OpenMind_Team2#69]
- [x] 메인페이지에서 질문 받기 눌렀을때 answer페이지로 이동하는 과정에서 화면이 안보이는 현상 해결
    ㄴ app.js 라우팅 수정 
- [x] answer 페이지에서 로컬스토리지에서 id 꺼내오는 로직 추가

**Comment by Nahyun-Kang** [comment]
확인했습니당..! 고생하셨습니다bb
