### ISSUE TITLE
[1차] QA

### ISSUE THREAD

**Issue by ParkSohyunee** [Team2-Project-OpenMind/OpenMind_Team2#89]
- [x] 랜딩페이지 백그라운드 - 유진
- [x] 배너에 로고 추가 - 유진
- [x] 질문받기 클릭시 /post/{id}/answer 페이지로 이동 - 민섭
- [x] 메인페이지 아이디 입력하면 이미 가입여부 검증 작업 해제, 대신 로컬스토리지에 저장(ex. key - '나현', value - '198') - 민섭
- [x] list 페이지 [답변하러가기] 버튼 호버시 드롭다운 혹은 팝오버처럼 로컬스토리지에 저장된 아이디 목록이 보여지고 그중 선택해서 답변하러가기 - 민섭
- [x] post 페이지 이동시 배너가 바로 안뜨고 새로고침해야 나옴 - 민섭
- [x] 아초는 고양이(즉, 프로필 이름) 질문 작성하기 또는 post 페이지에서 이름 나오기 - 민섭
- [x] 클립보드 복사 토스트 fixed로 위치 고정 - 나현
- [x] 답변페이지는 답변 거절일때 거절사유가 나오는 부분을 -> 답변거절로 나오게 수정 - 나현
- [x] 답변페이지 좋아요, 싫어요 0일때는 숫자 안보여지기 - 민혁
- [x] 답변페이지 답변 거절 부분 - 거절했을때 바로 페이지에 반영 여부 - 민혁

**Comment by namminimi** [comment]
list 페이지 [답변하러가기] 버튼 호버시 드롭다운 혹은 팝오버처럼 로컬스토리지에 저장된 아이디 목록이 보여지고 그중 선택해서 답변하러가기 - 스타일 미완이지만 시간 괜찮으실 때 pull 받아서 확인해주세요👍(local에 저장된 객체 구조는 app.js에 주석처리 했습니다,)
